apiVersion: batch/v1
kind: Job
metadata:
  name: config-agent-test
spec:
  template:
    spec:
      serviceAccountName: secret-sync-controller
      volumes:
      - name: config-volume
        configMap:
          name: config
      containers:
      - name: sync-container
        image: gcr.io/k8s-jkns-gke-soak/secret-sync-controller:latest
        command: ["sh", "-c", "cd pkg/config && go test -v --e2e --config-path=/tmp/config/syncConfig"]
        volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: /tmp/config
      restartPolicy: Never