apiVersion: batch/v1
kind: Job
metadata:
  name: secret-sync-controller
spec:
  template:
    spec:
      serviceAccountName: secret-sync-controller
      volumes:
      - name: config-volume
        configMap:
          name: config
      containers:
      - name: sync-container
        image: gcr.io/k8s-staging-k8s-gsm-tools/secret-sync-controller:latest
        command: 
        - /app
        args:
        - --config-path=/tmp/config/syncConfig 
        - --period=1000
        - --v=2
        volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: /tmp/config
      restartPolicy: Never