kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: secret-sync-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: secret-sync-role-binding
subjects:
- kind: ServiceAccount
  namespace: default
  name: secret-sync-controller
roleRef:
 kind: ClusterRole
 name: secret-sync-role
 apiGroup: rbac.authorization.k8s.io